name: donut_chart
version: 0.1.0
homepage: https://github.com/marchdev-tk/donut_chart
description: Donut chart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0

flutter:
  uses-material-design: true
